Repository grupo-ispc-2023-2-0/workflix-app, pull requests merged in 2023-10, with the labels that each got.

#166 [ADD] nuevo logo - workflix
  workflix/app/src/main/ic_launcher-playstore.png
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/restablecer/RestablecerActivity.java
  workflix/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  workflix/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  workflix/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  workflix/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  workflix/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  workflix/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  workflix/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  workflix/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  workflix/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  workflix/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  workflix/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  workflix/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  workflix/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  workflix/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  workflix/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  workflix/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  workflix/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  workflix/app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#176 Delete persona
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/models/Persona.java
  workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  workflix/app/src/main/java/tec/ispc/workflix/utils/PersonaService.java
  workflix/app/src/main/java/tec/ispc/workflix/views/FalsoMain.java
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/PersonaActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/PersonaAdapter.java
  workflix/app/src/main/res/layout/activity_falso_main.xml
  workflix/app/src/main/res/layout/content_main.xml
  workflix/app/src/main/res/layout/persona_layout.xml
Labels: bug

#178 Backend
  backend/workflix/.gitignore
  backend/workflix/.mvn/wrapper/maven-wrapper.jar
  backend/workflix/.mvn/wrapper/maven-wrapper.properties
  backend/workflix/mvnw
  backend/workflix/mvnw.cmd
  backend/workflix/pom.xml
  backend/workflix/src/main/java/com/tec/workflix/WorkflixApplication.java
  backend/workflix/src/main/java/com/tec/workflix/controllers/UsuarioController.java
  backend/workflix/src/main/java/com/tec/workflix/interfaces/IUsuarioInterface.java
  backend/workflix/src/main/java/com/tec/workflix/models/Profesional.java
  backend/workflix/src/main/java/com/tec/workflix/models/Usuario.java
  backend/workflix/src/main/java/com/tec/workflix/modelsDAO/UsuarioDAO.java
  backend/workflix/src/main/java/com/tec/workflix/services/UsuarioService.java
  backend/workflix/src/main/resources/application.properties
  backend/workflix/src/test/java/com/tec/workflix/WorkflixApplicationTests.java
  workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardActivity.java
Labels: bug

#186 agrega conexion registro usuario
  workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#187 Tk60 conexion de registracion
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/res/layout/activity_register.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#189 Tk61 validacion campos registracion
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#190 Login
  backend/workflix/pom.xml
  backend/workflix/src/main/java/com/tec/workflix/controllers/LoginApiController.java
  backend/workflix/src/main/java/com/tec/workflix/controllers/RegisterApiController.java
  backend/workflix/src/main/java/com/tec/workflix/controllers/UsuarioController.java
  backend/workflix/src/main/java/com/tec/workflix/models/Login.java
  backend/workflix/src/main/java/com/tec/workflix/models/Users.java
  backend/workflix/src/main/java/com/tec/workflix/repository/IUsuarioRepository.java
  backend/workflix/src/main/java/com/tec/workflix/services/UsuarioService.java
  backend/workflix/src/main/resources/application.properties
  backend/workflix/src/main/resources/db_script/main.sql
  backend/workflix/src/main/resources/logback.xml
  workflix/app/build.gradle.kts
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/CrearPerfilActivity.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
  workflix/app/src/main/res/layout/activity_login.xml
Labels: enhancement

#197 elimina model users, creado para testear
  backend/workflix/src/main/java/com/tec/workflix/models/Users.java
  backend/workflix/src/main/java/com/tec/workflix/repository/IUsuarioRepository.java
Labels: bug

#200 Corregir activity restablecer
  workflix/app/src/main/res/layout/activity_restablecer.xml
  workflix/app/src/main/res/values/strings.xml
Labels: bug

#201 agrega conexion register con back
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
Labels: enhancement

#209 Lombok
  backend/workflix/pom.xml
  backend/workflix/src/main/java/com/tec/workflix/models/Login.java
  backend/workflix/src/main/java/com/tec/workflix/models/Profesional.java
  backend/workflix/src/main/java/com/tec/workflix/models/Usuario.java
  workflix/app/build.gradle.kts
  workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
Labels: enhancement

#210 Vincular register con back
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
Labels: enhancement

#215 Ref dev back
  backend/workflix/src/main/java/com/tec/workflix/controllers/RegisterApiController.java
  backend/workflix/src/main/java/com/tec/workflix/models/Profesional.java
  backend/workflix/src/main/java/com/tec/workflix/models/Usuario.java
  backend/workflix/src/main/resources/logback.xml
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/eliminar_cuenta/EliminarCuentaActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/CrearPerfilActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
  workflix/app/src/main/res/layout/fragment_home.xml
Labels: enhancement

#218 217 tk73 quitar lombok
  backend/workflix/pom.xml
  backend/workflix/src/main/java/com/tec/workflix/models/Login.java
  backend/workflix/src/main/java/com/tec/workflix/models/Usuario.java
  workflix/app/build.gradle.kts
  workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
Labels: invalid

#220 Agregando funcionalidades al dashboard
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/UsuarioActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/UsuarioAdapter.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardUsuariosActivity.java
  workflix/app/src/main/res/drawable/dashboard_add.xml
  workflix/app/src/main/res/drawable/dashboard_admin.xml
  workflix/app/src/main/res/drawable/dashboard_close.xml
  workflix/app/src/main/res/drawable/dashboard_delete.xml
  workflix/app/src/main/res/drawable/dashboard_see.xml
  workflix/app/src/main/res/drawable/dashboard_services.xml
  workflix/app/src/main/res/drawable/dashboard_update.xml
  workflix/app/src/main/res/drawable/dashboard_users.xml
  workflix/app/src/main/res/layout/dashboard_admin.xml
  workflix/app/src/main/res/layout/dashboard_usuarios.xml
Labels: enhancement

#225 Tk38 crear tarjeta ampliada
  documentos/ui-tarjeta-ampliada.png
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/models/Profesional.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/CatalogoActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/ProfesionalAdapter.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/TarjetaAmpliadaActivity.java
  workflix/app/src/main/res/layout/activity_tarjeta_ampliada.xml
  workflix/app/src/main/res/layout/tarjeta_profesional.xml
Labels: enhancement

#226 Tk72 arreglar perfil
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/terminosCondiciones.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
  workflix/app/src/main/res/layout/activity_perfil_terminos.xml
Labels: enhancement

#229 Crear modelo servicio backend
  backend/workflix/src/main/java/com/tec/workflix/controllers/ServicioController.java
  backend/workflix/src/main/java/com/tec/workflix/interfaces/IServicioInterface.java
  backend/workflix/src/main/java/com/tec/workflix/models/Servicio.java
  backend/workflix/src/main/java/com/tec/workflix/modelsDAO/ServicioDAO.java
  backend/workflix/src/main/java/com/tec/workflix/services/ServicioService.java
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/models/Servicio.java
  workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  workflix/app/src/main/java/tec/ispc/workflix/utils/ServicioService.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/ServicioActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/ServicioAdapter.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardServiciosActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardUsuariosActivity.java
  workflix/app/src/main/res/layout/activity_dashboard_servicios.xml
  workflix/app/src/main/res/layout/activity_listar_servicios.xml
  workflix/app/src/main/res/layout/activity_servicio.xml
  workflix/app/src/main/res/layout/content_listar_servicios.xml
  workflix/app/src/main/res/layout/dashboard_admin.xml
Labels: enhancement

#233 se resuelve bug de duplicacion de app por tarjeta ampliada en Android…
  workflix/app/src/main/AndroidManifest.xml
Labels: bug

#234 Tk79 validar campos login
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
Labels: enhancement

#235 se corrige bug servicios
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/ServicioAdapter.java
Labels: bug

#236 se arregla bug de design en la tarjeta ampliada
  workflix/app/src/main/res/layout/activity_tarjeta_ampliada.xml
Labels: bug

#244 Se agrego el fondo blanco a la activity de tarjeta ampliada
  workflix/app/src/main/res/layout/activity_tarjeta_ampliada.xml
Labels: bug

#247 Se crea formulario de contacto
  workflix/app/src/main/res/layout/fragment_contact_mail.xml
  workflix/app/src/main/res/values/datos_spinner.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#254 Se quito el atributo onclick en las cardviews de administradores y ce…
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardUsuariosActivity.java
  workflix/app/src/main/res/layout/dashboard_admin.xml
Labels: bug

#259 Tk84 agregar texto debajo de telefono
  workflix/app/src/main/res/drawable/borde_edit_text.xml
  workflix/app/src/main/res/layout/activity_register.xml
  workflix/app/src/main/res/values/colors.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#262 Tk90 hacer activity responsive
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_perfil_terminos.xml
  workflix/app/src/main/res/layout/activity_register.xml
  workflix/app/src/main/res/layout/activity_restablecer.xml
  workflix/app/src/main/res/layout/fragment_contact_mail.xml
  workflix/app/src/main/res/layout/fragment_home.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#264 Se modifica fondo diagrama casos de uso
  documentos/diagrama_casos_uso_workflix.png
Labels: documentation

#265 Se edita casos de uso según roles
  documentos/Diagrama_casos_de_uso_workflix.png
  documentos/diagrama_casos_uso_workflix.png
Labels: documentation

#266 Ocultar perfil admin
  backend/workflix/src/main/java/com/tec/workflix/models/Usuario.java
  workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
  workflix/app/src/main/res/drawable/nav_dashboard.xml
Labels: enhancement

#269 [ADD] ocultar INGRESAR cuando ya se logeo el usuario
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
Labels: bug

#270 Funcionalidad a cerrar sesion en dashboard
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
  workflix/app/src/main/res/layout/dashboard_admin.xml
Labels: enhancement

#271 Arreglar validacion de mail a bd
  backend/workflix/src/main/java/com/tec/workflix/WorkflixApplication.java
  backend/workflix/src/main/java/com/tec/workflix/controllers/RegisterApiController.java
Labels: bug

#275 Eliminar en perfil
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
Labels: enhancement

#276 se da funcionalidad a boton enviar en formulario de contacto
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/ContactMail.java
Labels: enhancement

#278 se centra botón de enviar en formulario contacto.
  workflix/app/src/main/res/layout/fragment_contact_mail.xml
Labels: enhancement

#280 Tk96 crear vista principal de dashboard admin xml tal cual como se hizó con servicios y usuarios
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminVistaActivity.java
  workflix/app/src/main/res/layout/activity_dashboard_admin_vista.xml
  workflix/app/src/main/res/layout/activity_listar_administradores.xml
  workflix/app/src/main/res/layout/content_listar_administradores.xml
  workflix/app/src/main/res/layout/dashboard_admin.xml
Labels: enhancement

#287 Traer los campos faltantes al front desde models
  workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
Labels: enhancement

#289 Solucionar bug null en perfil
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
Labels: bug

#290 Dashboard usuarios mostrar profesionales
  workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/back/UsuarioAdapter.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardUsuariosActivity.java
Labels: bug

#293 Tk104 dashboard admin filtrar admin
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminVistaActivity.java
Labels: bug

#294 Tk112 agregar parent a todas las vistas
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
Labels: bug

#296 [ADD] solucion bug de registro - redireccion - testing ok
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
Labels: bug

#299 Tk97 video actual... sobre nosotros
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/AboutFragment.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/video/videoRaw.java
  workflix/app/src/main/res/layout/activity_video_raw.xml
  workflix/app/src/main/res/layout/fragment_about.xml
  workflix/app/src/main/res/raw/worflixvideo.mp4
Labels: enhancement

#300 Darle funcionalidad boton modificar perfil
  backend/workflix/src/main/java/com/tec/workflix/controllers/UsuarioController.java
  backend/workflix/src/main/java/com/tec/workflix/interfaces/IUsuarioInterface.java
  backend/workflix/src/main/java/com/tec/workflix/modelsDAO/UsuarioDAO.java
  backend/workflix/src/main/java/com/tec/workflix/services/UsuarioService.java
  workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
  workflix/app/src/main/java/tec/ispc/workflix/utils/UsuarioService.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
Labels: enhancement

#301 Subir foto perfil
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
Labels: enhancement

#307 Tk110 cambio imagen por genérica
  workflix/app/src/main/res/drawable/perfil_imagen.png
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
Labels: enhancement

#308 modifica datos descripción en perfil terminos
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
Labels: bug

#309 Tk108 crear video de testing en sellenium
  documentos/Imagenes/ui-tarjeta-ampliada.png
  documentos/Testing/test_saucedemo.side
Labels: documentation

#313 Guardar fotos
  backend/workflix/src/main/java/com/tec/workflix/modelsDAO/UsuarioDAO.java
  workflix/app/build.gradle.kts
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
Labels: enhancement

#315 Tk118 mostrar foto de perfil
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
  workflix/app/src/main/res/layout/activity_perfil_terminos.xml
Labels: enhancement

#316 quita ratingbar
  workflix/app/src/main/res/layout/activity_perfil_terminos.xml
Labels: bug

#317 306 tk114 rediseño del catalogo con funcionalidad
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/CatalogoActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/CatalogoAdapter.java
  workflix/app/src/main/res/layout/activity_catalogo.xml
  workflix/app/src/main/res/layout/tarjeta_profesional.xml
Labels: enhancement

#319 Se elimina el searchView del catalogo al no contar con ninguna funcio…
  workflix/app/src/main/res/layout/activity_catalogo.xml
Labels: bug

#321 Setear valores null preferences
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
Labels: bug

#325 corrige errores de visualización
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#327 agrega y corrige documentacion y testing
  documentos/Documento_ieee_830_WorkflixApp.pdf
  documentos/Testing/Accesibilidad aplicada a la App de Workflix.pdf
  documentos/diagama_relacional_workflix.png
  documentos/diagrama_DER_workflix.png
  documentos/diagrama_de_clases_workflix.png
  documentos/diagrama_relacional_workflix.png
Labels: documentation

#328 Refactor y bug tarjeta ampliada
  workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/CatalogoActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/CatalogoAdapter.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/ProfesionalAdapter.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/TarjetaAmpliadaActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
  workflix/app/src/main/res/layout/activity_tarjeta_ampliada.xml
  workflix/app/src/main/res/layout/tarjeta_profesional.xml
  workflix/app/src/main/res/values/estilos_personalizados.xml
Labels: bug
