Repository grupo-ispc-2023-2-0/workflix-app, pull requests merged in 2023-09, with the labels that each got.

#74 73 tk33 agregar gitignore
  .gitignore
Labels: enhancement

#75 agrega diagrama de clases a documentos
  documentos/Diagrama de clases - Workflix.png
Labels: documentation

#98 Agregando imagenes del prototipo alta y media
  documentos/Conexiones Prototipo.png
  documentos/Prototipo Alta.png
  documentos/Prototipo Media - Baja.png
Labels: documentation

#100 [ADD] solucion de bugs - creacion back plantilla login
  workflix/app/build.gradle.kts
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/data/LoginDataSource.java
  workflix/app/src/main/java/tec/ispc/workflix/views/data/LoginRepository.java
  workflix/app/src/main/java/tec/ispc/workflix/views/data/Result.java
  workflix/app/src/main/java/tec/ispc/workflix/views/data/model/LoggedInUser.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoggedInUserView.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginFormState.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginResult.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginViewModel.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginViewModelFactory.java
  workflix/app/src/main/res/layout-w1240dp/activity_login.xml
  workflix/app/src/main/res/layout-w936dp/activity_login.xml
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_main.xml
  workflix/app/src/main/res/values-land/dimens.xml
  workflix/app/src/main/res/values-w1240dp/dimens.xml
  workflix/app/src/main/res/values-w600dp/dimens.xml
  workflix/app/src/main/res/values/dimens.xml
  workflix/app/src/main/res/values/strings.xml
Labels: bug

#102 Rama natalia
  workflix/app/src/main/res/drawable/logo_workflix_1.png
  workflix/app/src/main/res/drawable/menu_01.png
  workflix/app/src/main/res/drawable/user_profile_circle.png
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/values/colors.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#104 cambia colores de texto
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/values/colors.xml
Labels: enhancement

#105 Braian home
  workflix/.idea/deploymentTargetDropDown.xml
  workflix/app/build.gradle.kts
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/archivo_vacio.txt
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/AboutFragment.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/HomeFragment.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/SettingsFragment.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/ShareFragment.java
  workflix/app/src/main/res/drawable/nav_about.xml
  workflix/app/src/main/res/drawable/nav_home.xml
  workflix/app/src/main/res/drawable/nav_logout.xml
  workflix/app/src/main/res/drawable/nav_settings.xml
  workflix/app/src/main/res/drawable/nav_share.xml
  workflix/app/src/main/res/layout/fragment_about.xml
  workflix/app/src/main/res/layout/fragment_home.xml
  workflix/app/src/main/res/layout/fragment_settings.xml
  workflix/app/src/main/res/layout/fragment_share.xml
  workflix/app/src/main/res/layout/nav_header.xml
  workflix/app/src/main/res/menu/nav_menu.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#106 activity registro
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#107 Braian home
  documentos/profesional.jpg
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/AboutFragment.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/HomeFragment.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/SettingsFragment.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/ShareFragment.java
  workflix/app/src/main/res/drawable/green_banner.png
  workflix/app/src/main/res/drawable/home_banner.jpg
  workflix/app/src/main/res/drawable/nav_login.xml
  workflix/app/src/main/res/layout/activity_main.xml
  workflix/app/src/main/res/layout/custom_toolbar.xml
  workflix/app/src/main/res/layout/fragment_about.xml
  workflix/app/src/main/res/layout/fragment_home.xml
  workflix/app/src/main/res/layout/fragment_settings.xml
  workflix/app/src/main/res/layout/fragment_share.xml
  workflix/app/src/main/res/layout/nav_header.xml
  workflix/app/src/main/res/menu/nav_menu.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#109 armado inicial de pagina de registro
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#110 [ADD] correcion colores
  workflix/app/src/main/res/layout/fragment_home.xml
Labels: enhancement

#111 Braian home
  workflix/.idea/render.experimental.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/ContactMail.java
  workflix/app/src/main/res/drawable/nav_contact_mail.xml
  workflix/app/src/main/res/layout/fragment_contact_mail.xml
  workflix/app/src/main/res/menu/nav_menu.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#112 agrega intent a registro y login
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#114 agrega dependencias entre activitys
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_register.xml
  workflix/app/src/main/res/values/themes.xml
Labels: enhancement

#117 Rama natalia
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/values/themes.xml
  workflix/app/src/main/res/values/themes2.xml
Labels: enhancement

#121 acomoda texto y botones en login
  workflix/.idea/misc.xml
  workflix/app/src/main/res/layout/activity_login.xml
Labels: enhancement

#122 cambia visualizacion login y registro
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#123 Darle funcionalidad a home
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/AboutFragment.java
  workflix/app/src/main/res/layout/fragment_about.xml
  workflix/app/src/main/res/layout/fragment_contact_mail.xml
  workflix/app/src/main/res/menu/nav_menu.xml
  workflix/app/src/main/res/values/colors.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#124 agrega intent
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_register.xml
Labels: enhancement

#126 [ADD] funcion para salir de la app
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
Labels: enhancement

#130 66 tk28 activity de restablecer
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/restablecer/RestablecerActivity.java
  workflix/app/src/main/res/layout/activity_restablecer.xml
Labels: enhancement

#131 Rama natalia
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_restablecer.xml
Labels: enhancement

#132 Valentino
  workflix/app/src/main/res/layout/activity_perfil_editar.xml
Labels: enhancement

#134 agrega activity parent a android manifest
  workflix/app/src/main/AndroidManifest.xml
Labels: enhancement

#136 133 tk55 conectar activity s
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
Labels: enhancement

#135 Refactorizacion
  documentos/logo.ico
  workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  workflix/app/src/main/res/drawable/nav_profile.xml
  workflix/app/src/main/res/menu/nav_menu.xml
Labels: enhancement

#138 [ADD] vinculacion intent
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/HomeFragment.java
Labels: enhancement

#140 Tk34 catalogo
  workflix/app/src/main/AndroidManifest.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/CatalogoActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/HomeFragment.java
  workflix/app/src/main/res/drawable/filtersbutton_style.xml
  workflix/app/src/main/res/drawable/flecha_derecha_filter.png
  workflix/app/src/main/res/drawable/flecha_izquierda_filter.png
  workflix/app/src/main/res/drawable/searchview_border.xml
  workflix/app/src/main/res/layout/activity_catalogo.xml
  workflix/app/src/main/res/values/dimens.xml
Labels: enhancement

#143 133 tk55 conec activity s
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/CrearPerfilActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/EditarPerfil.java
  workflix/app/src/main/res/layout/activity_perfil_editar.xml
Labels: enhancement

#148 Tk56 arreglos varios
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/restablecer/RestablecerActivity.java
  workflix/app/src/main/res/layout/activity_login.xml
  workflix/app/src/main/res/layout/activity_restablecer.xml
Labels: enhancement

#150 Refactorizar perfil
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
  workflix/app/src/main/res/layout/activity_perfil_terminos.xml
  workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#154 Tk58 documentacion sprint1
  documentos/Documento_ieee_830_WorkflixApp.pdf
  documentos/Imagenes/Grupo_trabajo.png
  documentos/Imagenes/banner-workflixApp-home.jpg
  documentos/Imagenes/banner_intro.png
  documentos/Imagenes/green_banner.png
  documentos/Imagenes/login_banner.png
  documentos/Imagenes/logo.ico
  documentos/Imagenes/profesional-1.jpg
  documentos/Imagenes/profesional-2.jpg
  documentos/Imagenes/profesional-3.jpg
  documentos/Imagenes/profesional-4.jpg
  documentos/Imagenes/profesional-5.jpg
  documentos/Imagenes/profesional.jpg
  documentos/Prototipo_conexion.png
  documentos/diagrama_casos_uso_workflix.png
  documentos/diagrama_de_clases_workflix.png
  documentos/diagrama_entidad_relacion_workfix.jpg
  documentos/diagrama_relacional_workflix.png
Labels: documentation

#155 cambiando color de texto de Descripcion en las tarjetas de los profes…
  workflix/app/src/main/res/layout/activity_catalogo.xml
  workflix/app/src/main/res/values/estilos_personalizados.xml
Labels: enhancement

#157 Eliminando y corrigiendo archivos
  workflix/.idea/misc.xml
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/CrearPerfilActivity.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/EditarPerfil.java
  workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
  workflix/app/src/main/res/layout/activity_crear_perfil.xml
  workflix/app/src/main/res/layout/activity_perfil_editar.xml
  workflix/app/src/main/res/layout/activity_perfil_terminos.xml
Labels: bug
